# Generated by Django 5.0.1 on 2025-01-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='Delivery_address',
        ),
    ]
